// templates/static-site/src/client/components/Layout.svelte
<script lang="ts">
  import StaticLink from './StaticLink.svelte'

  let path = $state(typeof window !== 'undefined' ? window.location.pathname : '/')
</script>

<div class="app-layout">
  <header class="main-header">
    <div class="container">
      <StaticLink href="/" className="brand">
        🚀 Gravito Static Site
      </StaticLink>
      <nav>
        <StaticLink href="/" className={path === '/' ? 'active' : ''}>
          Home
        </StaticLink>
        <StaticLink href="/about" className={path.startsWith('/about') ? 'active' : ''}>
          About
        </StaticLink>
      </nav>
    </div>
  </header>

  <main><slot /></main>

  <footer class="main-footer">
    <div class="container">
      Built with
      <a href="https://github.com/gravito-framework/gravito" target="_blank" rel="noopener">
        Gravito
      </a>
      + Inertia + Svelte (Static Site)
    </div>
  </footer>
</div>

// templates/inertia-vue/src/client/components/Layout.vue
<template>
  <div class="app-layout">
    <header class="main-header">
      <div class="container">
        <StaticLink href="/" class="brand">
          🚀 Gravito
        </StaticLink>
        <nav>
          <StaticLink href="/" :class="{ active: isHome }">
            Home
          </StaticLink>
          <StaticLink href="/about" :class="{ active: isAbout }">
            About
          </StaticLink>
        </nav>
      </div>
    </header>

    <main><slot /></main>

    <footer class="main-footer">
      <div class="container">
        Built with
        <a href="https://github.com/GravitoJS" target="_blank" rel="noopener">
          Gravito
        </a>
        + Inertia + Vue
      </div>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { usePage } from '@inertiajs/vue3'
import { computed } from 'vue'

const page = usePage()
const isHome = computed(() => page.url === '/')
const isAbout = computed(() => page.url.startsWith('/about'))
</script>
