// examples/luminosity-site/src/client/pages/Privacy.vue
<script setup lang="ts">
import { Head } from '@inertiajs/vue3'
import { Shield, Lock, Eye } from 'lucide-vue-next'
import Layout from '../components/Layout.vue'
import { useI18n } from '../composables/useI18n'

const { t } = useI18n()
</script>

<template>
  <Layout>
    <Head>
      <title>Privacy Policy | Luminosity</title>
    </Head>

    <section class="relative pt-32 pb-20 overflow-hidden bg-black min-h-screen">
      <!-- Ambient Background -->
      <div class="absolute inset-0 z-0">
        <div class="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[600px] bg-emerald-500/10 rounded-full blur-[120px] -translate-y-1/2" />
      </div>

      <div class="max-w-4xl mx-auto px-6 relative z-10">
        <div class="text-center mb-16">
          <h1 class="text-5xl lg:text-7xl font-black italic tracking-tighter mb-4 text-white uppercase">
            {{ t?.legal?.privacy?.title }}
          </h1>
          <p class="text-emerald-500 font-mono text-xs uppercase tracking-widest">
            {{ t?.legal?.privacy?.lastUpdated }}
          </p>
        </div>

        <div class="space-y-8">
          <!-- Section 1 -->
          <div class="p-8 rounded-[32px] bg-white/[0.02] border border-white/5 backdrop-blur-sm hover:border-emerald-500/20 transition-all group">
            <div class="flex flex-col md:flex-row gap-6">
              <div class="w-14 h-14 rounded-2xl bg-emerald-500/10 flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform">
                <Shield class="w-7 h-7 text-emerald-500" />
              </div>
              <div>
                <h2 class="text-2xl font-bold mb-4 text-white uppercase italic tracking-tight">
                  {{ t?.legal?.privacy?.section1?.title }}
                </h2>
                <p class="text-gray-400 leading-relaxed font-light text-lg">
                  {{ t?.legal?.privacy?.section1?.content }}
                </p>
              </div>
            </div>
          </div>

          <!-- Section 2 -->
          <div class="p-8 rounded-[32px] bg-white/[0.02] border border-white/5 backdrop-blur-sm hover:border-emerald-500/20 transition-all group">
            <div class="flex flex-col md:flex-row gap-6">
              <div class="w-14 h-14 rounded-2xl bg-emerald-500/10 flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform">
                <Lock class="w-7 h-7 text-emerald-500" />
              </div>
              <div>
                <h2 class="text-2xl font-bold mb-4 text-white uppercase italic tracking-tight">
                  {{ t?.legal?.privacy?.section2?.title }}
                </h2>
                <p class="text-gray-400 leading-relaxed font-light text-lg">
                  {{ t?.legal?.privacy?.section2?.content }}
                </p>
              </div>
            </div>
          </div>

          <!-- Section 3 -->
          <div class="p-8 rounded-[32px] bg-white/[0.02] border border-white/5 backdrop-blur-sm hover:border-emerald-500/20 transition-all group">
            <div class="flex flex-col md:flex-row gap-6">
              <div class="w-14 h-14 rounded-2xl bg-emerald-500/10 flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform">
                <Eye class="w-7 h-7 text-emerald-500" />
              </div>
              <div>
                <h2 class="text-2xl font-bold mb-4 text-white uppercase italic tracking-tight">
                  {{ t?.legal?.privacy?.section3?.title }}
                </h2>
                <p class="text-gray-400 leading-relaxed font-light text-lg">
                  {{ t?.legal?.privacy?.section3?.content }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </Layout>
</template>

// examples/official-site/src/client/pages/Privacy.tsx
import { Head } from '@inertiajs/react'
import { Fingerprint, Lock, Shield, Sparkles } from 'lucide-react'
import Layout from '../components/Layout'
import { useTrans } from '../hooks/useTrans'

export default function Privacy() {
  const { trans } = useTrans()

  return (
    <Layout>
      <Head>
        <title>{trans('legal.privacy.title')} | Gravito Framework</title>
      </Head>

      <section className="relative pt-32 pb-20 overflow-hidden bg-void min-h-screen">
        {/* Celestial Background */}
        <div className="absolute inset-0 z-0">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[600px] bg-singularity/10 rounded-full blur-[120px] -translate-y-1/2" />
        </div>

        <div className="max-w-4xl mx-auto px-6 relative z-10">
          <div className="text-center mb-16">
            <h1 className="text-5xl lg:text-7xl font-black italic tracking-tighter mb-4 text-white uppercase">
              {trans('legal.privacy.title')}
            </h1>
            <p className="text-singularity font-mono text-xs uppercase tracking-[0.3em]">
              {trans('legal.privacy.lastUpdated')}
            </p>
          </div>

          <div className="space-y-12">
            {/* Section 1 */}
            <div className="group p-8 rounded-[2rem] bg-white/[0.02] border border-white/5 backdrop-blur-3xl hover:border-singularity/30 transition-all duration-500">
              <div className="flex items-center gap-4 mb-6">
                <div className="p-3 rounded-xl bg-singularity/10 text-singularity group-hover:scale-110 transition-transform">
                  <Shield size={24} />
                </div>
                <h2 className="text-2xl font-bold tracking-tight text-white">
                  {trans('legal.privacy.section1.title')}
                </h2>
              </div>
              <p className="text-gray-400 leading-relaxed text-lg">
                {trans('legal.privacy.section1.content')}
              </p>
            </div>

            {/* Section 2 */}
            <div className="group p-8 rounded-[2rem] bg-white/[0.02] border border-white/5 backdrop-blur-3xl hover:border-singularity/30 transition-all duration-500">
              <div className="flex items-center gap-4 mb-6">
                <div className="p-3 rounded-xl bg-singularity/10 text-singularity group-hover:scale-110 transition-transform">
                  <Fingerprint size={24} />
                </div>
                <h2 className="text-2xl font-bold tracking-tight text-white">
                  {trans('legal.privacy.section2.title')}
                </h2>
              </div>
              <p className="text-gray-400 leading-relaxed text-lg">
                {trans('legal.privacy.section2.content')}
              </p>
            </div>

            {/* Section 3 */}
            <div className="group p-8 rounded-[2rem] bg-white/[0.02] border border-white/5 backdrop-blur-3xl hover:border-singularity/30 transition-all duration-500">
              <div className="flex items-center gap-4 mb-6">
                <div className="p-3 rounded-xl bg-singularity/10 text-singularity group-hover:scale-110 transition-transform">
                  <Lock size={24} />
                </div>
                <h2 className="text-2xl font-bold tracking-tight text-white">
                  {trans('legal.privacy.section3.title')}
                </h2>
              </div>
              <p className="text-gray-400 leading-relaxed text-lg">
                {trans('legal.privacy.section3.content')}
              </p>
            </div>

            {/* Section 4 */}
            <div className="group p-8 rounded-[2rem] bg-white/[0.02] border border-white/5 backdrop-blur-3xl hover:border-singularity/30 transition-all duration-500">
              <div className="flex items-center gap-4 mb-6">
                <div className="p-3 rounded-xl bg-singularity/10 text-singularity group-hover:scale-110 transition-transform">
                  <Sparkles size={24} />
                </div>
                <h2 className="text-2xl font-bold tracking-tight text-white">
                  {trans('legal.privacy.section4.title')}
                </h2>
              </div>
              <p className="text-gray-400 leading-relaxed text-lg">
                {trans('legal.privacy.section4.content')}
              </p>
            </div>
          </div>

          <div className="mt-20 p-8 rounded-[2rem] bg-singularity/5 border border-singularity/10 text-center">
            <p className="text-sm font-mono text-singularity uppercase tracking-widest">
              Secure Protocol Active {'//'} {new Date().getFullYear()}
            </p>
          </div>
        </div>
      </section>
    </Layout>
  )
}
