// examples/official-site/src/client/pages/About.tsx
import { Head } from '@inertiajs/react'

import Layout from '../components/Layout'

export default function About() {
  return (
    <Layout>
      <Head title="About - Gravito" />

      <div className="container" style={{ textAlign: 'center' }}>
        <div className="features">
          <h2>✨ Why Gravito?</h2>

          <div className="feature-grid">
            <div className="feature-card">
              <span className="icon">⚡️</span>
              <h3>Super Fast</h3>
              <p>Powered by Bun and Hono for extreme performance.</p>
            </div>
            <div className="feature-card">
              <span className="icon">⚛️</span>
              <h3>Modern Stack</h3>
              <p>React, Interia.js, and TypeScript out of the box.</p>
            </div>
            <div className="feature-card">
              <span className="icon">🎨</span>
              <h3>Beautiful</h3>
              <p>Includes modern CSS variables and dark mode support.</p>
            </div>
          </div>
        </div>

        <div style={{ marginTop: '3rem' }}>
          <p className="tagline">This page was loaded via Inertia without a full page reload!</p>
        </div>
      </div>
    </Layout>
  )
}

// templates/inertia-vue/src/client/pages/About.vue
<template>
  <Layout>
    <Head title="About - Gravito Vue" />

    <div class="container" style="text-align: center">
      <div class="features">
        <h2>✨ Why Gravito?</h2>

        <div class="feature-grid">
          <div class="feature-card">
            <span class="icon">⚡️</span>
            <h3>Super Fast</h3>
            <p>Powered by Bun and Photon for extreme performance.</p>
          </div>
          <div class="feature-card">
            <span class="icon">🟢</span>
            <h3>Vue 3 Stack</h3>
            <p>Vue 3, Interia.js, and TypeScript out of the box.</p>
          </div>
          <div class="feature-card">
            <span class="icon">🎨</span>
            <h3>Beautiful</h3>
            <p>Includes modern CSS variables and dark mode support.</p>
          </div>
        </div>
      </div>

      <div style="margin-top: 3rem">
        <p class="tagline">This page was loaded via Inertia without a full page reload!</p>
      </div>
    </div>
  </Layout>
</template>

<script setup lang="ts">
import { Head } from '@inertiajs/vue3'
import Layout from '../components/Layout.vue'
</script>
