// examples/atlas-site/src/client/components/Footer.vue
<template>
  <footer class="py-12 relative z-10 border-t border-white/10 bg-black">
    <div class="max-w-7xl mx-auto px-8 flex flex-col md:flex-row justify-between items-center opacity-60 hover:opacity-100 transition-opacity">
        <div class="flex items-center gap-2 mb-4 md:mb-0">
            <span class="text-xl font-bold font-mono text-white">@gravito/<span class="text-atlas-cyan">atlas</span></span>
            <span class="text-xs text-gray-500 ml-2">v0.0.1</span>
        </div>
        <div class="text-sm text-gray-500">
            &copy; 2025 Gravito Framework. MIT License.
        </div>
    </div>
  </footer>
</template>

// examples/zenith-site/src/client/components/Footer.tsx
import { LayoutDashboard } from 'lucide-react'
import React from 'react'
import { StaticLink } from './StaticLink'
import { useTrans } from '../hooks/useTrans'

export function Footer() {
    const { trans, locale } = useTrans()

    return (
        <footer className="border-t border-white/5 py-16 bg-zenith-void relative overflow-hidden">
            <div className="absolute bottom-0 left-1/4 w-[600px] h-[300px] bg-zenith-500/10 rounded-full blur-[100px] translate-y-1/2" />

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
                <div className="flex flex-col md:flex-row justify-between items-center gap-8">
                    <div className="flex items-center gap-3 text-gray-400">
                        <div className="w-10 h-10 rounded bg-gradient-to-br from-zenith-500/20 to-zenith-stellar/20 flex items-center justify-center border border-white/10">
                            <LayoutDashboard className="w-6 h-6 text-zenith-accent" />
                        </div>
                        <div>
                            <span className="font-bold text-white block tracking-widest text-lg">ZENITH</span>
                            <span className="text-xs uppercase tracking-tighter opacity-50">Control Plane</span>
                        </div>
                    </div>
                    <div className="flex gap-8 text-gray-400 text-sm font-medium">
                        <StaticLink href={locale === 'zh-TW' ? '/zh-TW' : '/'} className="hover:text-zenith-accent transition-colors">
                            {trans('footer.privacy')}
                        </StaticLink>
                        <StaticLink href={locale === 'zh-TW' ? '/zh-TW' : '/'} className="hover:text-zenith-accent transition-colors">
                            {trans('footer.terms')}
                        </StaticLink>
                        <StaticLink href={locale === 'zh-TW' ? '/zh-TW' : '/'} className="hover:text-zenith-accent transition-colors">
                            {trans('footer.contact')}
                        </StaticLink>
                    </div>
                    <div className="text-gray-500 text-xs font-mono">{trans('footer.copyright')}</div>
                </div>
            </div>
        </footer>
    )
}
