// examples/zenith-site/src/client/pages/Home.tsx
import { usePage } from '@inertiajs/react'
import { StaticLink } from '../components/StaticLink'
import { motion } from 'framer-motion'
import {
  Activity,
  AlertCircle,
  ArrowRight,
  BookOpen,
  Clock,
  Database,
  Github,
  Globe,
  LayoutDashboard,
  Search,
  Server,
  Zap,
} from 'lucide-react'
import React from 'react'
import { useTrans } from '../hooks/useTrans'

interface HomeProps {
  t?: any
  locale?: string
  version?: string
}

export default function Home() {
  const { trans, locale } = useTrans()
  const props = usePage<HomeProps>().props
  return (
    <div className="min-h-screen bg-zenith-900 text-white selection:bg-zenith-accent selection:text-zenith-900 overflow-x-hidden font-sans">
      {/* Navigation */}
      <nav className="fixed w-full z-50 border-b border-white/10 bg-zenith-900/80 backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded bg-gradient-to-br from-zenith-500 to-zenith-accent flex items-center justify-center">
                <LayoutDashboard className="w-5 h-5 text-white" />
              </div>
              <span className="text-xl font-bold tracking-wider">ZENITH</span>
            </div>
            <div className="hidden md:flex items-center gap-8 text-sm font-medium text-gray-400">
              <StaticLink href={locale === 'zh-TW' ? '/zh-TW' : '/'} className="hover:text-white transition-colors">
                {trans('nav.features')}
              </StaticLink>
              <StaticLink href={locale === 'zh-TW' ? '/zh-TW' : '/'} className="hover:text-white transition-colors">
                {trans('nav.integration')}
              </StaticLink>
              <StaticLink href={locale === 'zh-TW' ? '/zh-TW' : '/'} className="hover:text-white transition-colors">
                {trans('nav.docs')}
              </StaticLink>
              <StaticLink
                href={locale === 'zh-TW' ? '/zh-TW/about' : '/about'}
                className="hover:text-white transition-colors"
              >
                {trans('nav.about')}
              </StaticLink>
            </div>
            <div className="flex items-center gap-4">
              {/* Language Switcher */}
              <div className="relative group">
                <button
                  type="button"
                  className="p-2 hover:bg-white/10 rounded-full transition-colors flex items-center gap-1"
                >
                  <Globe className="w-5 h-5" />
                  <span className="text-xs font-mono">{locale === 'zh-TW' ? '繁中' : 'EN'}</span>
                </button>
                <div className="absolute right-0 top-full mt-2 w-32 bg-zenith-800 border border-white/10 rounded-lg shadow-xl opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all z-50">
                  <StaticLink
                    href={locale === 'zh-TW' ? '/' : '/zh-TW'}
                    className="block px-4 py-2 text-sm hover:bg-white/10 transition-colors text-left"
                  >
                    {locale === 'zh-TW' ? 'English' : '繁體中文'}
                  </StaticLink>
                  <StaticLink
                    href={locale === 'zh-TW' ? '/about' : '/zh-TW/about'}
                    className="block px-4 py-2 text-sm hover:bg-white/10 transition-colors text-left border-t border-white/5"
                  >
                    {locale === 'zh-TW' ? 'About (EN)' : '關於 (繁中)'}
                  </StaticLink>
                </div>
              </div>
              <a
                href="https://github.com/gravito-work/gravito"
                target="_blank"
                rel="noopener noreferrer"
                className="p-2 hover:bg-white/10 rounded-full transition-colors"
              >
                <Github className="w-5 h-5" />
              </a>
              <button
                type="button"
                className="hidden md:flex items-center gap-2 bg-white/10 hover:bg-white/20 px-4 py-2 rounded text-sm font-medium transition-colors border border-white/10"
              >
                <span>v{props.version || '0.1.0'}</span>
              </button>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative pt-32 pb-20 lg:pt-48 lg:pb-32 overflow-hidden">
        {/* Background Gradients */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-7xl h-full pointer-events-none">
          <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-zenith-500/20 rounded-full blur-[100px]" />
          <div className="absolute bottom-0 right-1/4 w-[500px] h-[500px] bg-zenith-accent/10 rounded-full blur-[100px]" />
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="flex flex-col lg:flex-row items-center gap-16">
            {/* Hero Content */}
            <div className="flex-1 text-center lg:text-left">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
              >
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-zenith-500/10 border border-zenith-500/20 text-zenith-400 text-xs font-mono mb-6">
                  <span className="relative flex h-2 w-2">
                    <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-zenith-accent opacity-75"></span>
                    <span className="relative inline-flex rounded-full h-2 w-2 bg-zenith-accent"></span>
                  </span>
                  {trans('hero.status')}
                </div>
                <h1 className="text-5xl lg:text-7xl font-bold tracking-tight mb-6 leading-tight">
                  {trans('hero.title')} <br />
                  <span className="text-transparent bg-clip-text bg-gradient-to-r from-zenith-400 to-zenith-accent">
                    {trans('hero.titleHighlight')}
                  </span>
                </h1>
                <p className="text-lg text-gray-400 mb-8 max-w-2xl mx-auto lg:mx-0 leading-relaxed">
                  {trans('hero.description')}
                </p>

                <div className="flex flex-col sm:flex-row items-center gap-4 justify-center lg:justify-start">
                  <button
                    type="button"
                    className="w-full sm:w-auto px-8 py-3 bg-zenith-500 hover:bg-zenith-400 text-white rounded font-medium transition-all shadow-lg shadow-zenith-500/25 flex items-center justify-center gap-2 group"
                  >
                    {trans('hero.getStarted')}{' '}
                    <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                  </button>
                  <button
                    type="button"
                    className="w-full sm:w-auto px-8 py-3 bg-transparent border border-white/20 hover:bg-white/5 text-white rounded font-medium transition-colors flex items-center justify-center gap-2"
                  >
                    <BookOpen className="w-4 h-4" /> {trans('hero.documentation')}
                  </button>
                </div>
              </motion.div>
            </div>

            {/* Hero Visual - Dashboard Mockup */}
            <div className="flex-1 w-full max-w-lg lg:max-w-none">
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.7, delay: 0.2 }}
                className="relative rounded-xl border border-white/10 bg-black/50 backdrop-blur-xl p-4 shadow-2xl"
              >
                {/* Mockup Header */}
                <div className="flex items-center justify-between mb-4 border-b border-white/5 pb-4">
                  <div className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full bg-red-500" />
                    <div className="w-3 h-3 rounded-full bg-yellow-500" />
                    <div className="w-3 h-3 rounded-full bg-green-500" />
                  </div>
                  <div className="text-xs text-gray-500 font-mono">zenith-dashboard.local</div>
                </div>

                {/* Mockup Content Grid */}
                <div className="grid grid-cols-2 gap-4">
                  {/* Stat Card 1 */}
                  <div className="bg-white/5 p-4 rounded border border-white/5">
                    <div className="text-xs text-gray-400 uppercase tracking-wider mb-2">
                      Throughput
                    </div>
                    <div className="text-2xl font-mono font-bold text-zenith-accent flex items-baseline gap-2">
                      12,450 <span className="text-xs text-gray-500 font-sans">ops/sec</span>
                    </div>
                    <div className="h-1 w-full bg-white/10 mt-2 rounded overflow-hidden">
                      <div className="h-full w-3/4 bg-zenith-accent rounded animate-pulse" />
                    </div>
                  </div>

                  {/* Stat Card 2 */}
                  <div className="bg-white/5 p-4 rounded border border-white/5">
                    <div className="text-xs text-gray-400 uppercase tracking-wider mb-2">
                      Active Workers
                    </div>
                    <div className="text-2xl font-mono font-bold text-green-400 flex items-baseline gap-2">
                      48 <span className="text-xs text-gray-500 font-sans">nodes</span>
                    </div>
                    <div className="flex gap-1 mt-3">
                      {[1, 2, 3, 4, 5, 6].map((i) => (
                        <div key={i} className="h-2 w-2 rounded-full bg-green-400 opacity-80" />
                      ))}
                    </div>
                  </div>

                  {/* Queue List */}
                  <div className="col-span-2 bg-white/5 p-4 rounded border border-white/5">
                    <div className="flex items-center justify-between mb-3">
                      <div className="text-xs text-gray-400 uppercase tracking-wider">
                        Active Queues
                      </div>
                      <div className="text-xs text-zenith-500">View All</div>
                    </div>
                    <div className="space-y-2">
                      {['emails.transactional', 'images.process', 'analytics.batch'].map((q, i) => (
                        <div
                          key={q}
                          className="flex items-center justify-between p-2 bg-black/20 rounded"
                        >
                          <div className="flex items-center gap-2">
                            <div
                              className={`w-1.5 h-1.5 rounded-full ${i === 0 ? 'bg-green-400' : 'bg-zenith-accent'}`}
                            />
                            <span className="text-sm font-mono text-gray-300">{q}</span>
                          </div>
                          <span className="text-xs text-gray-500 font-mono">
                            {Math.floor(Math.random() * 1000)} jobs
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </motion.div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-24 bg-black/20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl lg:text-4xl font-bold mb-4">{trans('features.title')}</h2>
            <p className="text-gray-400 text-lg max-w-2xl mx-auto">{trans('features.subtitle')}</p>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            <FeatureCard
              icon={<Activity />}
              title={trans('features.realtimeMonitoring.title')}
              description={trans('features.realtimeMonitoring.description')}
            />
            <FeatureCard
              icon={<Server />}
              title={trans('features.queueManagement.title')}
              description={trans('features.queueManagement.description')}
            />
            <FeatureCard
              icon={<Search />}
              title={trans('features.jobAuditing.title')}
              description={trans('features.jobAuditing.description')}
            />
            <FeatureCard
              icon={<Database />}
              title={trans('features.dlqOperations.title')}
              description={trans('features.dlqOperations.description')}
            />
            <FeatureCard
              icon={<AlertCircle />}
              title={trans('features.automatedAlerting.title')}
              description={trans('features.automatedAlerting.description')}
            />
            <FeatureCard
              icon={<Clock />}
              title={trans('features.scheduleManagement.title')}
              description={trans('features.scheduleManagement.description')}
            />
          </div>
        </div>
      </section>

      {/* Code Snippet Section */}
      <section className="py-24 border-t border-white/5">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col lg:flex-row items-center gap-16">
            <div className="flex-1">
              <h2 className="text-3xl font-bold mb-6">{trans('integration.title')}</h2>
              <p className="text-gray-400 mb-8 text-lg">{trans('integration.description')}</p>

              <ul className="space-y-4">
                <ListItem text={trans('integration.features.autoDiscovery')} />
                <ListItem text={trans('integration.features.sqliteSupport')} />
                <ListItem text={trans('integration.features.workerHealth')} />
                <ListItem text={trans('integration.features.logArchiving')} />
                <ListItem text={trans('integration.features.batchActions')} />
                <ListItem text={trans('integration.features.hybridSearch')} />
              </ul>
            </div>

            <div className="flex-1 w-full">
              <div className="bg-[#0d1117] rounded-lg border border-white/10 p-6 font-mono text-sm overflow-x-auto">
                <div className="flex gap-2 mb-4">
                  <div className="w-3 h-3 rounded-full bg-red-500/20" />
                  <div className="w-3 h-3 rounded-full bg-yellow-500/20" />
                  <div className="w-3 h-3 rounded-full bg-green-500/20" />
                </div>
                <pre className="text-gray-300">
                  <code>
                    <div className="line">
                      <span className="text-purple-400">import</span> {'{'} Zenith {'}'}{' '}
                      <span className="text-purple-400">from</span>{' '}
                      <span className="text-green-400">'@gravito/zenith'</span>
                    </div>
                    <div className="line">
                      <span className="text-purple-400">import</span> {'{'} App {'}'}{' '}
                      <span className="text-purple-400">from</span>{' '}
                      <span className="text-green-400">'./app'</span>
                    </div>
                    <div className="line h-4"></div>
                    <div className="line">
                      <span className="text-gray-500">{'// Initialize Zenith with your app'}</span>
                    </div>
                    <div className="line">
                      <span className="text-blue-400">const</span> zenith ={' '}
                      <span className="text-purple-400">new</span> Zenith(App)
                    </div>
                    <div className="line h-4"></div>
                    <div className="line">
                      <span className="text-gray-500">{'// Mount the dashboard'}</span>
                    </div>
                    <div className="line">
                      zenith.mount(<span className="text-green-400">"/admin/zenith"</span>)
                    </div>
                    <div className="line h-4"></div>
                    <div className="line">
                      <span className="text-gray-500">{'// Start the control plane'}</span>
                    </div>
                    <div className="line">
                      <span className="text-purple-400">await</span> zenith.start()
                    </div>
                  </code>
                </pre>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/10 py-12 bg-black/40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2 text-gray-400">
            <LayoutDashboard className="w-5 h-5" />
            <span className="font-bold text-white">ZENITH</span>
            <span>{trans('footer.copyright')}</span>
          </div>
          <div className="flex gap-6 text-gray-400 text-sm">
            <StaticLink href={locale === 'zh-TW' ? '/zh-TW' : '/'} className="hover:text-white transition-colors">
              {trans('footer.privacy')}
            </StaticLink>
            <StaticLink href={locale === 'zh-TW' ? '/zh-TW' : '/'} className="hover:text-white transition-colors">
              {trans('footer.terms')}
            </StaticLink>
            <StaticLink href={locale === 'zh-TW' ? '/zh-TW' : '/'} className="hover:text-white transition-colors">
              {trans('footer.contact')}
            </StaticLink>
          </div>
        </div>
      </footer>
    </div>
  )
}

function FeatureCard({
  icon,
  title,
  description,
}: {
  icon: React.ReactNode
  title: string
  description: string
}) {
  return (
    <div className="p-6 rounded-lg bg-white/5 border border-white/5 hover:border-zenith-500/50 hover:bg-white/10 transition-all group">
      <div className="w-12 h-12 rounded bg-zenith-500/20 flex items-center justify-center text-zenith-400 mb-4 group-hover:text-zenith-accent group-hover:scale-110 transition-all">
        {React.cloneElement(icon as React.ReactElement<{ className?: string }>, {
          className: 'w-6 h-6',
        })}
      </div>
      <h3 className="text-xl font-bold mb-2">{title}</h3>
      <p className="text-gray-400 leading-relaxed">{description}</p>
    </div>
  )
}

function ListItem({ text }: { text: string }) {
  return (
    <li className="flex items-center gap-3 text-gray-300">
      <div className="w-5 h-5 rounded-full bg-zenith-500/20 flex items-center justify-center text-zenith-400 flex-shrink-0">
        <Zap className="w-3 h-3" />
      </div>
      {text}
    </li>
  )
}

// examples/luminosity-site/src/client/pages/Home.vue
<script setup lang="ts">
import { Head } from '@inertiajs/vue3';
import { Activity, Zap, HardDrive, FileText, ChevronRight, Share2, Shield, Search } from 'lucide-vue-next';
import { StaticLink } from '@gravito/freeze-vue';
import { Image } from '@gravito/prism/vue';
import Layout from '../components/Layout.vue';
import Logo from '../components/Logo.vue';
import { useI18n } from '../composables/useI18n';
import heroGraphic from '../assets/hero-graphic.png';
import gridSvg from '../assets/grid.svg';

defineProps<{
  message?: string
}>();

const { t, locale } = useI18n()
</script>

<template>
  <Layout>
    <Head>
      <title>{{ t?.hero?.title }} - Luminosity SEO</title>
      <meta name="description" :content="t?.hero?.subtitle + ' - ' + t?.hero?.desc" />
      
      <!-- Open Graph / Facebook -->
      <meta property="og:type" content="website" />
      <meta property="og:url" content="https://lux.gravito.dev/" />
      <meta property="og:title" :content="t?.hero?.title + ' - Luminosity SEO'" />
      <meta property="og:description" :content="t?.hero?.subtitle" />
      <meta property="og:image" content="https://lux.gravito.dev/og-image.png" />

      <!-- Twitter -->
      <meta property="twitter:card" content="summary_large_image" />
      <meta property="twitter:url" content="https://lux.gravito.dev/" />
      <meta property="twitter:title" :content="t?.hero?.title + ' - Luminosity SEO'" />
      <meta property="twitter:description" :content="t?.hero?.subtitle" />
      <meta property="twitter:image" content="https://lux.gravito.dev/og-image.png" />
    </Head>
    
    <!-- Hero Section -->
    <section class="relative min-h-screen flex items-center justify-center overflow-hidden pt-20">
      <!-- Background Effects -->
      <div class="absolute inset-0 z-0">
        <!-- Main Hero Graphic (Full Screen) -->
        <div class="absolute inset-0 opacity-50 pointer-events-none select-none">
          <Image 
            :src="heroGraphic" 
            alt="Luminosity Core" 
            class="w-full h-full object-cover animate-pulse-slow"
            loading="eager"
            fetchpriority="high"
          />
        </div>
        
        <!-- Overlays for Readability & Mood -->
        <div class="absolute inset-0 bg-void/60 mix-blend-multiply"></div>
        <div class="absolute inset-0 bg-gradient-to-b from-void/80 via-transparent to-void"></div>
        <div class="absolute inset-0 opacity-10 mix-blend-overlay" :style="{ backgroundImage: `url(${gridSvg})` }"></div>
      </div>
      
      <!-- Content -->
      <div class="relative z-10 text-center px-6 max-w-5xl mx-auto mt-20">
        <div 
          class="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-emerald-500/20 bg-emerald-500/5 text-emerald-400 text-xs font-mono tracking-widest uppercase mb-6 backdrop-blur-sm animate-fade-in"
        >
          <span class="w-2 h-2 rounded-full bg-emerald-500 animate-ping"></span>
          {{ t?.hero?.tag }}
        </div>
        
        <h1 class="text-6xl md:text-9xl font-black tracking-tighter mb-8 leading-[0.9] text-white">
          {{ t?.hero?.title }} <br />
          <span class="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 via-green-500 to-emerald-600">{{ t?.hero?.subtitle }}</span>
        </h1>
        
        <p class="text-xl md:text-2xl text-gray-400 max-w-3xl mx-auto mb-16 font-light leading-relaxed">
          {{ t?.hero?.desc }}
        </p>
        
        <div class="flex flex-col sm:flex-row gap-6 justify-center items-center">
          <StaticLink 
            href="/docs/getting-started"
            class="w-full sm:w-auto px-10 py-5 bg-white text-black font-black rounded-2xl hover:scale-105 active:scale-95 transition-all shadow-[0_0_30px_rgba(255,255,255,0.2)] flex items-center justify-center gap-2"
          >
            {{ t?.hero?.ctaPro }} <ChevronRight :size="20" />
          </StaticLink>
          <StaticLink 
            href="/docs"
            class="w-full sm:w-auto px-10 py-5 border border-white/10 text-white font-bold rounded-2xl hover:bg-white/5 transition-all backdrop-blur-sm"
          >
            {{ t?.hero?.ctaDocs }}
          </StaticLink>
        </div>
      </div>

      <!-- Scroll Indicator -->
      <div class="absolute bottom-10 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 opacity-50">
        <span class="text-[10px] font-mono uppercase tracking-[0.3em]">{{ t?.scroll }}</span>
        <div class="w-[1px] h-12 bg-gradient-to-b from-emerald-500 to-transparent"></div>
      </div>
    </section>

    <!-- Features Bento -->
    <section id="features" class="py-32 relative">
      <div class="max-w-7xl mx-auto px-6">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div class="md:col-span-2 p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-md relative overflow-hidden group">
            <div class="absolute top-0 right-0 p-8 opacity-10 group-hover:scale-110 transition-transform duration-700">
               <Share2 :size="120" />
            </div>
            <div class="relative z-10">
              <div class="w-12 h-12 rounded-xl bg-emerald-500/20 flex items-center justify-center text-emerald-400 mb-6 font-bold">01</div>
              <h3 class="text-3xl font-bold mb-4">{{ t?.features?.lsm?.title }}</h3>
              <p class="text-gray-400 text-lg max-w-lg mb-6">
                {{ t?.features?.lsm?.desc }}
              </p>
            </div>
          </div>
          
          <div class="p-8 rounded-3xl bg-gradient-to-br from-emerald-600 to-green-700 border border-white/10 relative overflow-hidden group">
            <div class="relative z-10 h-full flex flex-col justify-between">
              <div>
                <Shield class="text-white/80 mb-6" :size="40" />
                <h3 class="text-2xl font-bold text-white mb-4">{{ t?.features?.enterprise?.title }}</h3>
                <p class="text-emerald-100/70 mb-6">
                  {{ t?.features?.enterprise?.desc }}
                </p>
              </div>
              <div class="pt-8 flex justify-end">
                <Logo size="lg" class="opacity-20 translate-x-12 translate-y-12 rotate-[-15deg] grayscale brightness-200" />
              </div>
            </div>
          </div>
          
          <div class="p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-md group">
            <Search class="text-emerald-500 mb-6" :size="32" />
            <h3 class="text-xl font-bold mb-2">{{ t?.features?.index?.title }}</h3>
            <p class="text-gray-500 text-sm mb-4">
              {{ t?.features?.index?.desc }}
            </p>
          </div>

          <div class="p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-md group">
            <Shield class="text-emerald-500 mb-6" :size="32" />
            <h3 class="text-xl font-bold mb-2">{{ t?.features?.proxy?.title }}</h3>
            <p class="text-gray-500 text-sm mb-4">
               {{ t?.features?.proxy?.desc }}
            </p>
          </div>

          <div class="p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-md group">
            <FileText class="text-emerald-500 mb-6" :size="32" />
            <h3 class="text-xl font-bold mb-2">{{ t?.features?.meta?.title }}</h3>
            <p class="text-gray-500 text-sm mb-4">
              {{ t?.features?.meta?.desc }}
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Benchmark Section -->
    <section class="py-32 bg-panel border-y border-white/5 relative overflow-hidden">
      <div class="max-w-7xl mx-auto px-6">
        
        <!-- Section Header -->
        <div class="text-center mb-24">
          <h2 class="text-5xl md:text-7xl font-black tracking-tighter mb-4 italic">
            {{ t?.benchmark?.title }} <span class="text-emerald-500">{{ t?.benchmark?.subtitle }}</span>
          </h2>
          <p class="text-gray-400 text-xl font-mono tracking-widest uppercase">{{ t?.benchmark?.metric }}</p>
        </div>

        <!-- Metrics Grid -->
        <div class="grid grid-cols-1 md:grid-cols-4 gap-6 mb-24">
          <div class="p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-sm group hover:border-emerald-500/50 transition-colors">
            <div class="flex items-center gap-3 mb-4 text-emerald-400">
              <FileText :size="20" />
              <span class="text-xs font-mono uppercase tracking-wider">{{ t?.benchmark?.urls }}</span>
            </div>
            <div class="text-5xl font-black text-white mb-2">1,000,000</div>
            <div class="text-xs text-gray-500 uppercase tracking-widest">Single Stream Scan</div>
          </div>

          <div class="p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-sm group hover:border-emerald-500/50 transition-colors">
            <div class="flex items-center gap-3 mb-4 text-blue-400">
              <Zap :size="20" />
              <span class="text-xs font-mono uppercase tracking-wider">{{ t?.benchmark?.throughput }}</span>
            </div>
            <div class="text-5xl font-black text-white mb-2">70k<span class="text-xl text-gray-500 italic ml-1">/sec</span></div>
            <div class="text-xs text-gray-500 uppercase tracking-widest">LSM-Optimized</div>
          </div>

          <div class="p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-sm group hover:border-emerald-500/50 transition-colors">
            <div class="flex items-center gap-3 mb-4 text-amber-400">
              <HardDrive :size="20" />
              <span class="text-xs font-mono uppercase tracking-wider">{{ t?.benchmark?.memory }}</span>
            </div>
            <div class="text-5xl font-black text-white mb-2">84<span class="text-xl text-gray-500 italic ml-1">MB</span></div>
            <div class="text-xs text-gray-500 uppercase tracking-widest">Constant Heap Usage</div>
          </div>

          <div class="p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-sm group hover:border-emerald-500/50 transition-colors">
            <div class="flex items-center gap-3 mb-4 text-purple-400">
              <Activity :size="20" />
              <span class="text-xs font-mono uppercase tracking-wider">{{ t?.benchmark?.build }}</span>
            </div>
            <div class="text-5xl font-black text-white mb-2">14.2<span class="text-xl text-gray-500 italic ml-1">s</span></div>
            <div class="text-xs text-gray-500 uppercase tracking-widest">100% Success Rate</div>
          </div>
        </div>

        <!-- Terminal Demo -->
        <div class="max-w-4xl mx-auto group">
          <div class="rounded-2xl overflow-hidden border border-white/10 bg-void shadow-[0_0_50px_rgba(0,0,0,0.5)] group-hover:border-emerald-500/30 transition-all duration-700">
            <!-- Terminal Header -->
            <div class="bg-[#1A1A1A] px-6 py-4 flex items-center gap-3 border-b border-white/5">
              <div class="flex gap-2">
                <div class="w-3 h-3 rounded-full bg-red-500/50"></div>
                <div class="w-3 h-3 rounded-full bg-amber-500/50"></div>
                <div class="w-3 h-3 rounded-full bg-green-500/50"></div>
              </div>
              <div class="ml-4 text-xs font-mono text-gray-500">luminosity-benchmark — bun run benchmark</div>
            </div>
            
            <!-- Terminal Body -->
            <div class="p-8 font-mono text-sm leading-relaxed overflow-x-auto">
              <div class="text-gray-500 mb-2">$ bun run benchmark</div>
              <div class="text-emerald-400">🌌 [LUMINOSITY] Initializing Atomic Engine...</div>
              <div class="text-gray-600 mb-4">--------------------------------------------------</div>
              <div class="flex justify-between items-center mb-1">
                <div class="text-gray-300">🚀 Sequential Ops Log</div><div class="text-green-500">[COMPLETE]</div>
              </div>
              <div class="flex justify-between items-center mb-1">
                <div class="text-gray-300">🔥 Snapshot Merge</div><div class="text-green-500">[COMPLETE]</div>
              </div>
              <div class="flex justify-between items-center mb-4">
                <div class="text-gray-300">📦 XML Paginator</div><div class="text-green-500">[20 FILES]</div>
              </div>
              
              <div class="mt-8 border border-emerald-500/20 p-6 rounded-xl bg-emerald-500/5">
                <div class="text-emerald-400 font-black mb-4 tracking-widest text-center">FINAL REPORT</div>
                <div class="grid grid-cols-2 gap-x-8 gap-y-2 text-gray-400">
                  <div>Telescope Range</div><div class="text-right text-white font-bold">1,000,000 URLs</div>
                  <div>Build Velocity</div><div class="text-right text-white font-bold">14.2s TOTAL</div>
                  <div>Energy Signature</div><div class="text-right text-emerald-500 font-bold">84MB RAM</div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Full Report Link -->
        <div class="mt-12 text-center animate-fade-in" style="animation-delay: 0.5s">
          <StaticLink 
            href="/docs/benchmark"
            class="inline-flex items-center gap-2 px-6 py-3 rounded-full border border-emerald-500/30 bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 hover:scale-105 transition-all font-mono text-sm group"
          >
            <FileText :size="16" />
            <span class="group-hover:underline underline-offset-4">
              {{ locale === 'zh' ? '查看完整基準測試報告' : 'View Full Benchmark Report' }}
            </span>
            <ChevronRight :size="16" class="group-hover:translate-x-1 transition-transform" />
          </StaticLink>
        </div>

      </div>
    </section>
  </Layout>
</template>

<style>
@keyframes fade-in {
  from { opacity: 0; transform: translateY(10px); }
  to { opacity: 1; transform: translateY(0); }
}

.animate-fade-in {
  animation: fade-in 1s ease-out forwards;
}

@keyframes pulse-slow {
  0%, 100% { opacity: 0.6; transform: scale(1); }
  50% { opacity: 0.8; transform: scale(1.02); }
}

.animate-pulse-slow {
  animation: pulse-slow 8s infinite ease-in-out;
}
</style>
