// templates/inertia-react/src/client/components/Layout.tsx
import type React from 'react'
import { StaticLink } from './StaticLink'

export default function Layout({ children }: { children: React.ReactNode }) {
  // Determine active link based on current path
  // Note: In real Inertia app, you might use usePage().url
  const path = typeof window !== 'undefined' ? window.location.pathname : '/'

  return (
    <div className="app-layout">
      <header className="main-header">
        <div className="container">
          <StaticLink href="/" className="brand">
            🚀 Gravito
          </StaticLink>
          <nav>
            <StaticLink href="/" className={path === '/' ? 'active' : ''}>
              Home
            </StaticLink>
            <StaticLink href="/about" className={path.startsWith('/about') ? 'active' : ''}>
              About
            </StaticLink>
          </nav>
        </div>
      </header>

      <main>{children}</main>

      <footer className="main-footer">
        <div className="container">
          Built with{' '}
          <a href="https://github.com/GravitoJS" target="_blank" rel="noopener">
            Gravito
          </a>{' '}
          + Inertia + React
        </div>
      </footer>
    </div>
  )
}

// templates/static-site/src/client/components/Layout.vue
<template>
  <div class="app-layout">
    <header class="main-header">
      <div class="container">
        <StaticLink href="/" class="brand"> 🚀 Gravito Static Site </StaticLink>
        <nav>
          <StaticLink href="/" :class="{ active: path === '/' }"> Home </StaticLink>
          <StaticLink href="/about" :class="{ active: path.startsWith('/about') }"> About </StaticLink>
        </nav>
      </div>
    </header>

    <main><slot /></main>

    <footer class="main-footer">
      <div class="container">
        Built with
        <a href="https://github.com/gravito-framework/gravito" target="_blank" rel="noopener">
          Gravito
        </a>
        + Inertia + Vue (Static Site)
      </div>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineProps<{ children?: any }>()

const path = computed(() => {
  if (typeof window !== 'undefined') {
    return window.location.pathname
  }
  return '/'
})
</script>
