// examples/luminosity-site/src/client/pages/Features.vue
<script setup lang="ts">
import { StaticLink } from '@gravito/freeze-vue'
import { Head } from '@inertiajs/vue3'
import {
  Activity,
  ChevronRight,
  Code,
  Cpu,
  Layers,
  Share2,
  Shield,
  Terminal,
  Zap,
} from 'lucide-vue-next'
import { computed } from 'vue'
import Layout from '../components/Layout.vue'
import { useI18n } from '../composables/useI18n'

const { t, locale } = useI18n()

const points = computed(() => [
  {
    icon: Zap,
    title: t.value?.features_page?.points?.atomic?.title,
    desc: t.value?.features_page?.points?.atomic?.desc,
    color: 'bg-emerald-500/20 text-emerald-400',
    docsLink: '/docs/architecture#atomic-sequential-writes',
  },
  {
    icon: Share2,
    title: t.value?.features_page?.points?.compaction?.title,
    desc: t.value?.features_page?.points?.compaction?.desc,
    color: 'bg-green-500/20 text-green-400',
    docsLink: '/docs/architecture#dynamic-compaction',
  },
  {
    icon: Activity,
    title: t.value?.features_page?.points?.zerocopy?.title,
    desc: t.value?.features_page?.points?.zerocopy?.desc,
    color: 'bg-teal-500/20 text-teal-400',
    docsLink: '/docs/architecture#zero-copy-serialization',
  },
  {
    icon: Layers,
    title: t.value?.features_page?.points?.tiered?.title,
    desc: t.value?.features_page?.points?.tiered?.desc,
    color: 'bg-emerald-600/20 text-emerald-300',
    docsLink: '/docs/architecture#tiered-storage',
  },
])
</script>

<template>
  <Layout>
    <Head>
      <title>Features | Luminosity</title>
    </Head>

    <!-- Hero Section -->
    <section class="relative py-32 px-6 overflow-hidden">
      <div class="absolute inset-0 bg-black">
        <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-emerald-500/10 rounded-full blur-[150px] animate-pulse" />
      </div>

      <div class="max-w-4xl mx-auto relative z-10 text-center">
        <div class="mb-8 inline-block">
          <div class="p-4 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-xl shadow-2xl relative group">
            <div class="absolute inset-0 bg-emerald-500/20 blur-xl opacity-0 group-hover:opacity-100 transition-opacity" />
            <Cpu :size="64" class="text-emerald-500 relative z-10" />
          </div>
        </div>

        <h1 class="text-6xl md:text-8xl font-black italic tracking-tighter text-white mb-6 uppercase">
          {{ t?.features_page?.hero?.title }} <span class="text-emerald-500">{{ t?.features_page?.hero?.highlight }}</span>
        </h1>

        <p class="text-xl text-gray-400 font-medium max-w-2xl mx-auto">
          {{ t?.features_page?.hero?.desc }}
        </p>
      </div>
    </section>

    <!-- Core Deep Dive -->
    <section class="relative py-24 px-6 bg-black z-20">
      <div class="max-w-6xl mx-auto">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-16 items-center mb-32">
          <div>
            <h2 class="text-4xl md:text-5xl font-black italic tracking-tighter text-white mb-8 uppercase">
              {{ t?.features_page?.core?.title }} <span class="text-emerald-500">{{ t?.features_page?.core?.highlight }}</span> {{ t?.features_page?.core?.suffix }}
            </h2>
            <p class="text-lg text-gray-400 leading-relaxed font-light">
              {{ t?.features_page?.core?.desc }}
            </p>

            <!-- Code Sample -->
            <div class="mt-12 p-8 rounded-[32px] bg-white/[0.02] border border-white/5 backdrop-blur-sm relative overflow-hidden group">
              <div class="absolute inset-x-0 bottom-0 h-1 bg-gradient-to-r from-transparent via-emerald-500 to-transparent opacity-30 group-hover:opacity-100 transition-opacity" />
              <div class="flex items-center gap-4 mb-6">
                <Terminal :size="24" class="text-emerald-500" />
                <span class="text-xs font-black text-gray-500 uppercase tracking-widest">
                  Luminosity Runtime
                </span>
              </div>
              <div class="font-mono text-sm space-y-2 text-gray-300">
                <div class="flex gap-4">
                  <span class="text-emerald-500 opacity-50">01</span>
                  <span>import { Luminosity } from '@gravito/luminosity'</span>
                </div>
                <div class="flex gap-4">
                  <span class="text-emerald-500 opacity-50">02</span>
                  <span>const engine = new Luminosity({ path: './db' })</span>
                </div>
                <div class="flex gap-4">
                  <span class="text-emerald-500 opacity-50">03</span>
                  <span>// High-speed atomic batch write</span>
                </div>
                <div class="flex gap-4 font-bold text-white">
                  <span class="text-emerald-500 opacity-50">04</span>
                  <span>await engine.writeBatch(records)</span>
                </div>
              </div>
            </div>
          </div>

          <!-- Feature Cards -->
          <div class="grid grid-cols-1 gap-6">
            <div
              v-for="(point, index) in points"
              :key="point.title"
              class="p-8 rounded-[24px] bg-white/[0.03] border border-white/10 hover:border-white/20 transition-all hover:bg-white/[0.05] group"
            >
              <div class="flex items-start gap-6">
                <div :class="`p-4 rounded-xl ${point.color} group-hover:scale-110 transition-transform` ">
                  <component :is="point.icon" :size="28" />
                </div>
                <div>
                  <h3 class="text-xl font-bold text-white mb-2">{{ point.title }}</h3>
                  <p class="text-gray-400 text-sm leading-relaxed mb-4">{{ point.desc }}</p>
                  <StaticLink 
                    :href="point.docsLink"
                    class="text-xs font-black uppercase tracking-widest text-emerald-500 hover:text-emerald-400 flex items-center gap-1 group/btn"
                  >
                    {{ locale === 'zh' ? '了解更多' : 'Learn More' }}
                    <ChevronRight :size="14" class="group-hover/btn:translate-x-1 transition-transform" />
                  </StaticLink>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Architecture Section -->
    <section class="relative py-24 px-6 bg-white/[0.02] border-y border-white/5 z-20">
      <div class="max-w-6xl mx-auto text-center mb-16">
        <h2 class="text-4xl md:text-5xl font-black italic tracking-tighter text-white mb-6 uppercase">
            {{ t?.features_page?.architecture?.title }} <span class="text-emerald-500">{{ t?.features_page?.architecture?.highlight }}</span>
        </h2>
        <p class="text-lg text-gray-400 leading-relaxed font-light max-w-3xl mx-auto">
            {{ t?.features_page?.architecture?.desc }}
        </p>
      </div>
      
      <div class="max-w-5xl mx-auto">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4 items-center">
            <!-- Step 1 -->
            <div class="p-6 rounded-2xl bg-black border border-white/10 text-center relative group">
                <div class="absolute -top-3 left-1/2 -translate-x-1/2 bg-emerald-500 text-black text-xs font-bold px-2 py-0.5 rounded-full">INPUT</div>
                <div class="mb-4 text-emerald-500 flex justify-center"><Activity :size="32" /></div>
                <div class="text-white font-bold">{{ t?.features_page?.architecture?.step1 }}</div>
                <div class="absolute right-[-1rem] top-1/2 -translate-y-1/2 text-gray-700 hidden md:block">
                   <ChevronRight :size="24" />
                </div>
            </div>
             <!-- Step 2 -->
             <div class="p-6 rounded-2xl bg-black border border-white/10 text-center relative group">
                <div class="mb-4 text-emerald-500 flex justify-center"><Zap :size="32" /></div>
                <div class="text-white font-bold">{{ t?.features_page?.architecture?.step2 }}</div>
                 <div class="absolute right-[-1rem] top-1/2 -translate-y-1/2 text-gray-700 hidden md:block">
                   <ChevronRight :size="24" />
                </div>
            </div>
             <!-- Step 3 -->
             <div class="p-6 rounded-2xl bg-black border border-white/10 text-center relative group">
                <div class="mb-4 text-emerald-500 flex justify-center"><Layers :size="32" /></div>
                <div class="text-white font-bold">{{ t?.features_page?.architecture?.step3 }}</div>
                 <div class="absolute right-[-1rem] top-1/2 -translate-y-1/2 text-gray-700 hidden md:block">
                   <ChevronRight :size="24" />
                </div>
            </div>
             <!-- Step 4 -->
             <div class="p-6 rounded-2xl bg-black border border-white/10 text-center relative group">
                <div class="absolute -top-3 left-1/2 -translate-x-1/2 bg-emerald-500 text-black text-xs font-bold px-2 py-0.5 rounded-full">OUTPUT</div>
                <div class="mb-4 text-emerald-500 flex justify-center"><Share2 :size="32" /></div>
                <div class="text-white font-bold">{{ t?.features_page?.architecture?.step4 }}</div>
            </div>
        </div>
      </div>
    </section>
    
    <!-- Governance Section -->
    <section class="relative py-24 px-6 bg-black z-20">
        <div class="max-w-6xl mx-auto">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-16 items-center">
                <div class="order-2 md:order-1">
                    <div class="relative group">
                         <div class="absolute inset-0 bg-emerald-500/10 blur-[80px] rounded-full group-hover:opacity-100 transition-opacity opacity-50" />
                        <div class="relative z-10 p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-xl">
                            <div class="flex items-center gap-4 mb-6 border-b border-white/5 pb-6">
                                <Shield :size="32" class="text-emerald-500" />
                                <div class="text-xl font-bold text-white">Security Shield Active</div>
                            </div>
                            <div class="space-y-4">
                                <div class="flex justify-between items-center text-sm">
                                    <span class="text-gray-400">Bot Traffic</span>
                                    <span class="text-emerald-400 font-mono">BLOCKED (429)</span>
                                </div>
                                <div class="w-full h-1 bg-white/10 rounded-full overflow-hidden">
                                    <div class="h-full bg-emerald-500 w-[12%]" />
                                </div>
                                 <div class="flex justify-between items-center text-sm">
                                    <span class="text-gray-400">Googlebot</span>
                                    <span class="text-emerald-400 font-mono">ALLOWED (200)</span>
                                </div>
                                <div class="w-full h-1 bg-white/10 rounded-full overflow-hidden">
                                    <div class="h-full bg-emerald-500 w-[85%]" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="order-1 md:order-2">
                    <h2 class="text-4xl md:text-5xl font-black italic tracking-tighter text-white mb-8 uppercase">
                    {{ t?.features_page?.governance?.title }} <span class="text-emerald-500">{{ t?.features_page?.governance?.highlight }}</span>
                    </h2>
                    <p class="text-lg text-gray-400 leading-relaxed font-light mb-12">
                     {{ t?.features_page?.governance?.desc }}
                    </p>
                    <div class="grid grid-cols-1 sm:grid-cols-2 gap-6">
                        <div class="p-6 rounded-2xl bg-white/[0.03] border-l-2 border-emerald-500">
                             <h4 class="text-white font-bold mb-2">{{ t?.features_page?.governance?.cards?.rate_limit?.title }}</h4>
                             <p class="text-sm text-gray-400">{{ t?.features_page?.governance?.cards?.rate_limit?.desc }}</p>
                        </div>
                        <div class="p-6 rounded-2xl bg-white/[0.03] border-l-2 border-emerald-500">
                             <h4 class="text-white font-bold mb-2">{{ t?.features_page?.governance?.cards?.stale?.title }}</h4>
                             <p class="text-sm text-gray-400">{{ t?.features_page?.governance?.cards?.stale?.desc }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- CLI Section -->
    <section class="relative py-24 px-6 bg-white/[0.02] border-t border-white/5 z-20">
        <div class="max-w-4xl mx-auto text-center">
             <h2 class="text-4xl md:text-5xl font-black italic tracking-tighter text-white mb-6 uppercase">
                {{ t?.features_page?.cli?.title }} <span class="text-emerald-500">{{ t?.features_page?.cli?.highlight }}</span>
            </h2>
            <p class="text-lg text-gray-400 mb-12">
                {{ t?.features_page?.cli?.desc }}
            </p>
            <div class="text-left bg-black rounded-xl border border-white/10 p-6 font-mono text-sm shadow-2xl overflow-hidden">
                <div class="flex gap-2 mb-4 border-b border-white/10 pb-4">
                    <div class="w-3 h-3 rounded-full bg-red-500" />
                    <div class="w-3 h-3 rounded-full bg-yellow-500" />
                    <div class="w-3 h-3 rounded-full bg-green-500" />
                </div>
                <div class="text-gray-300 space-y-2">
                    <div><span class="text-emerald-500">user@dev:~/project$</span> bun lux:stats</div>
                    <div class="pl-4 text-gray-500">
                        ┌  Luminosity Status<br>
                        │  <span class="text-white">Total URLs:</span> <span class="text-emerald-400">1,240,592</span><br>
                        │  <span class="text-white">Index Size:</span> <span class="text-emerald-400">45.2 MB</span><br>
                        │  <span class="text-white">Fragments:</span> <span class="text-emerald-400">12</span><br>
                        └  Ready.
                    </div>
                     <div><span class="text-emerald-500">user@dev:~/project$</span> bun lux:warm --force</div>
                     <div class="pl-4 text-gray-500">
                       <span class="text-emerald-400">✔</span> Compaction started...<br>
                       <span class="text-emerald-400">✔</span> Cache warming complete (142ms)
                     </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Bottom CTA -->
    <section class="py-32 px-6 text-center bg-black border-t border-white/5">
      <h2 class="text-3xl font-bold text-white mb-8">{{ t?.features_page?.cta?.title }}</h2>
      <StaticLink
        href="/docs/getting-started"
        class="px-10 py-4 bg-emerald-500 text-black font-black italic rounded-full hover:scale-105 active:scale-95 transition-all inline-block"
      >
        {{ t?.features_page?.cta?.btn }}
      </StaticLink>
    </section>
  </Layout>
</template>

// examples/zenith-site/src/client/pages/Features.tsx
import { Head } from '@inertiajs/react'
import { motion } from 'framer-motion'
import { Activity, Cpu, Database, Globe, HardDrive, Layers, Shield, Zap } from 'lucide-react'
import type React from 'react'
import { Footer } from '../components/Footer'
import { Navbar } from '../components/Navbar'
import { useTrans } from '../hooks/useTrans'

export default function Features() {
  const { trans, locale } = useTrans()

  return (
    <div className="min-h-screen bg-zenith-void text-white selection:bg-zenith-accent selection:text-zenith-void overflow-x-hidden font-sans">
      <Head title={`${trans('nav.features')} - Gravito Zenith`} />
      <Navbar />

      {/* Immersive Hero Section */}
      <section className="relative pt-40 pb-24 overflow-hidden">
        <div className="absolute inset-0 z-0">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-full bg-[radial-gradient(circle_at_center,rgba(0,240,255,0.08)_0%,transparent_70%)]" />
          <div className="absolute inset-0 bg-grid-zenith opacity-20" />
          {/* Animated Glows */}
          <div className="absolute -top-24 -left-24 w-96 h-96 bg-zenith-pulse/20 rounded-full blur-[120px] animate-pulse" />
          <div className="absolute top-1/2 right-0 w-[600px] h-[600px] bg-zenith-stellar/10 rounded-full blur-[150px]" />
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 text-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 1, ease: 'easeOut' }}
          >
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-zenith-accent/10 border border-zenith-accent/20 text-zenith-accent text-[10px] font-mono mb-8 tracking-[0.3em] uppercase">
              SYSTEM_SPEC_V1.4
            </div>
            <h1 className="text-5xl lg:text-7xl font-bold tracking-tight mb-8 leading-tight">
              {trans('features_deep.title')}{' '}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-zenith-400 via-zenith-accent to-zenith-stellar text-glow">
                {trans('features_deep.titleHighlight')}
              </span>
            </h1>
            <p className="text-xl text-gray-300 max-w-2xl mx-auto leading-relaxed font-light">
              {trans('features_deep.subtitle')}
            </p>
          </motion.div>
        </div>
      </section>

      {/* Persistence Architecture Visualization */}
      <section className="py-32 relative">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col md:flex-row items-center gap-12 mb-20">
            <div className="flex-1">
              <h2 className="text-4xl font-bold mb-6 tracking-tight">
                {trans('features_deep.persistence.title')}
              </h2>
              <p className="text-gray-300 text-lg font-light leading-relaxed">
                {trans('features_deep.persistence.description')}
              </p>
            </div>
            <div className="flex-none flex items-center gap-4 text-xs font-mono text-white/20">
              <div className="w-12 h-px bg-current" />
              DUAL_ENGINE_ACTIVE
              <div className="w-12 h-px bg-current" />
            </div>
          </div>

          <div className="grid lg:grid-cols-2 gap-8 relative">
            {/* Connecting Visual Line */}
            <div className="hidden lg:block absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-20 h-px bg-gradient-to-r from-zenith-pulse/50 to-zenith-stellar/50 z-0" />

            <motion.div
              whileHover={{ y: -5, borderColor: 'rgba(0, 240, 255, 0.3)' }}
              className="p-10 rounded-[2.5rem] zenith-glass relative group overflow-hidden z-10"
            >
              <div className="absolute top-0 right-0 w-48 h-48 bg-zenith-pulse/10 blur-[80px] rounded-full group-hover:scale-150 transition-transform duration-700" />
              <div className="w-16 h-16 rounded-2xl bg-zenith-pulse/10 flex items-center justify-center text-zenith-pulse mb-8 border border-zenith-pulse/20">
                <Layers size={32} />
              </div>
              <h3 className="text-2xl font-bold mb-4">
                {trans('features_deep.persistence.redis.title')}
              </h3>
              <p className="text-gray-300 leading-relaxed font-light text-lg">
                {trans('features_deep.persistence.redis.content')}
              </p>
              <div className="mt-10 flex items-center gap-6">
                <div className="flex flex-col">
                  <span className="text-[10px] font-mono text-white/30 uppercase tracking-widest">
                    Mode
                  </span>
                  <span className="text-zenith-pulse font-bold">TRANSIENT</span>
                </div>
                <div className="w-px h-8 bg-white/5" />
                <div className="flex flex-col">
                  <span className="text-[10px] font-mono text-white/30 uppercase tracking-widest">
                    Latency
                  </span>
                  <span className="text-zenith-pulse font-bold">&lt; 0.5ms</span>
                </div>
              </div>
            </motion.div>

            <motion.div
              whileHover={{ y: -5, borderColor: 'rgba(168, 85, 247, 0.3)' }}
              className="p-10 rounded-[2.5rem] zenith-glass relative group overflow-hidden z-10"
            >
              <div className="absolute top-0 right-0 w-48 h-48 bg-zenith-stellar/10 blur-[80px] rounded-full group-hover:scale-150 transition-transform duration-700" />
              <div className="w-16 h-16 rounded-2xl bg-zenith-stellar/10 flex items-center justify-center text-zenith-stellar mb-8 border border-zenith-stellar/20">
                <Database size={32} />
              </div>
              <h3 className="text-2xl font-bold mb-4">
                {trans('features_deep.persistence.sql.title')}
              </h3>
              <p className="text-gray-300 leading-relaxed font-light text-lg">
                {trans('features_deep.persistence.sql.content')}
              </p>
              <div className="mt-10 flex items-center gap-6">
                <div className="flex flex-col">
                  <span className="text-[10px] font-mono text-white/30 uppercase tracking-widest">
                    Mode
                  </span>
                  <span className="text-zenith-stellar font-bold">PERSISTENT</span>
                </div>
                <div className="w-px h-8 bg-white/5" />
                <div className="flex flex-col">
                  <span className="text-[10px] font-mono text-white/30 uppercase tracking-widest">
                    Durability
                  </span>
                  <span className="text-zenith-stellar font-bold">100% ACID</span>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* GPP Protocol - Blueprint Style */}
      <section className="py-32 relative overflow-hidden">
        <div className="absolute inset-0 bg-black/40 border-y border-white/5" />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="grid lg:grid-cols-12 gap-16 items-start">
            <div className="lg:col-span-5 space-y-8">
              <div className="w-20 h-20 rounded-3xl bg-zenith-accent/10 flex items-center justify-center text-zenith-accent border border-zenith-accent/20">
                <Zap size={40} className="animate-pulse" />
              </div>
              <h2 className="text-4xl font-bold tracking-tight">
                {trans('features_deep.protocol.title')}
              </h2>
              <p className="text-gray-300 text-lg font-light leading-relaxed">
                {trans('features_deep.protocol.description')}
              </p>

              <div className="p-8 rounded-3xl bg-black/40 border border-white/10 zenith-glass font-mono">
                <div className="flex items-center justify-between mb-6">
                  <span className="text-[10px] text-zenith-accent uppercase tracking-widest font-bold">
                    Protocol_Handshake
                  </span>
                  <div className="flex gap-1">
                    <div className="w-1 h-1 rounded-full bg-zenith-accent animate-ping" />
                    <div className="w-1 h-1 rounded-full bg-zenith-accent" />
                  </div>
                </div>
                <div className="space-y-3 text-[12px] text-gray-500">
                  <div className="flex justify-between">
                    <span>&gt; VERSION_REQUEST</span>
                    <span className="text-green-500">ACK_OK</span>
                  </div>
                  <div className="flex justify-between">
                    <span>&gt; ENCRYPTION_INIT</span>
                    <span className="text-green-500">CIPHER_READY</span>
                  </div>
                  <div className="flex justify-between">
                    <span>&gt; STREAM_SYNC</span>
                    <span className="text-zenith-accent">LINKED_STABLE</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="lg:col-span-7 grid sm:grid-cols-2 gap-6">
              <ProtocolFeature
                icon={<Zap className="w-6 h-6" />}
                title={trans('features_deep.protocol.feature1.title')}
                content={trans('features_deep.protocol.feature1.content')}
              />
              <ProtocolFeature
                icon={<Globe className="w-6 h-6" />}
                title={trans('features_deep.protocol.feature2.title')}
                content={trans('features_deep.protocol.feature2.content')}
              />
              <ProtocolFeature
                icon={<HardDrive className="w-6 h-6" />}
                title={trans('features_deep.protocol.feature3.title')}
                content={trans('features_deep.protocol.feature3.content')}
              />
              <ProtocolFeature
                icon={<Cpu className="w-6 h-6" />}
                title={locale === 'zh-TW' ? '超低開銷' : 'Ultra-Low Overhead'}
                content={
                  locale === 'zh-TW'
                    ? 'GPP 專為並發性能優化，確保監控本身不會成為系統的瓶頸。'
                    : 'GPP is optimized for concurrency, ensuring observability doesnt become a bottleneck.'
                }
              />
            </div>
          </div>
        </div>
      </section>

      {/* Performance Metrics - High-Tech Dashboard */}
      <section className="py-32 relative">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="zenith-glass-strong rounded-[3rem] p-16 border border-white/10 relative overflow-hidden group">
            {/* Background HUD Scan */}
            <div className="absolute inset-0 bg-grid-zenith opacity-10" />
            <div className="absolute inset-x-0 h-px bg-zenith-accent/30 top-1/2 -translate-y-1/2 animate-scanline" />

            <div className="relative z-10">
              <div className="text-center mb-16">
                <h2 className="text-sm font-mono tracking-[0.4em] uppercase text-white/30 mb-4">
                  System Performance Benchmarks
                </h2>
                <div className="w-24 h-1 bg-gradient-to-r from-transparent via-zenith-accent to-transparent mx-auto" />
              </div>

              <div className="grid md:grid-cols-3 gap-20">
                <MetricDisplay
                  value="< 0.1ms"
                  label={trans('features_deep.performance.latency')}
                  color="text-zenith-accent"
                  accent="bg-zenith-accent"
                />
                <MetricDisplay
                  value="50K+"
                  label={trans('features_deep.performance.throughput')}
                  color="text-green-400"
                  accent="bg-green-400"
                />
                <MetricDisplay
                  value="99.99%"
                  label={trans('features_deep.performance.reliability')}
                  color="text-zenith-stellar"
                  accent="bg-zenith-stellar"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}

function ProtocolFeature({
  icon,
  title,
  content,
}: {
  icon: React.ReactNode
  title: string
  content: string
}) {
  return (
    <motion.div
      whileHover={{ y: -5, scale: 1.02 }}
      className="p-8 rounded-3xl zenith-glass group transition-all"
    >
      <div className="w-12 h-12 rounded-2xl bg-white/5 flex items-center justify-center text-gray-400 mb-6 group-hover:text-zenith-accent group-hover:bg-zenith-accent/10 transition-all border border-white/5 group-hover:border-zenith-accent/20">
        {icon}
      </div>
      <h4 className="text-xl font-bold mb-3 tracking-tight">{title}</h4>
      <p className="text-sm text-gray-300 leading-relaxed font-light">{content}</p>
    </motion.div>
  )
}

function MetricDisplay({
  value,
  label,
  color,
  accent,
}: {
  value: string
  label: string
  color: string
  accent: string
}) {
  return (
    <div className="text-center space-y-4">
      <div
        className={`text-5xl lg:text-7xl font-mono font-bold ${color} tracking-tighter text-glow mb-2`}
      >
        {value}
      </div>
      <div className="flex items-center justify-center gap-3">
        <div className={`w-1.5 h-1.5 rounded-full ${accent} animate-pulse`} />
        <p className="text-xs font-mono text-gray-400 uppercase tracking-widest">{label}</p>
      </div>
    </div>
  )
}
