// examples/luminosity-site/src/client/pages/Privacy.vue
<script setup lang="ts">
import { Head } from '@inertiajs/vue3'
import { Shield, Lock, Eye } from 'lucide-vue-next'
import Layout from '../components/Layout.vue'
import { useI18n } from '../composables/useI18n'

const { t } = useI18n()
</script>

<template>
  <Layout>
    <Head>
      <title>Privacy Policy | Luminosity</title>
    </Head>

    <section class="relative pt-32 pb-20 overflow-hidden bg-black min-h-screen">
      <!-- Ambient Background -->
      <div class="absolute inset-0 z-0">
        <div class="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[600px] bg-emerald-500/10 rounded-full blur-[120px] -translate-y-1/2" />
      </div>

      <div class="max-w-4xl mx-auto px-6 relative z-10">
        <div class="text-center mb-16">
          <h1 class="text-5xl lg:text-7xl font-black italic tracking-tighter mb-4 text-white uppercase">
            {{ t?.legal?.privacy?.title }}
          </h1>
          <p class="text-emerald-500 font-mono text-xs uppercase tracking-widest">
            {{ t?.legal?.privacy?.lastUpdated }}
          </p>
        </div>

        <div class="space-y-8">
          <!-- Section 1 -->
          <div class="p-8 rounded-[32px] bg-white/[0.02] border border-white/5 backdrop-blur-sm hover:border-emerald-500/20 transition-all group">
            <div class="flex flex-col md:flex-row gap-6">
              <div class="w-14 h-14 rounded-2xl bg-emerald-500/10 flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform">
                <Shield class="w-7 h-7 text-emerald-500" />
              </div>
              <div>
                <h2 class="text-2xl font-bold mb-4 text-white uppercase italic tracking-tight">
                  {{ t?.legal?.privacy?.section1?.title }}
                </h2>
                <p class="text-gray-400 leading-relaxed font-light text-lg">
                  {{ t?.legal?.privacy?.section1?.content }}
                </p>
              </div>
            </div>
          </div>

          <!-- Section 2 -->
          <div class="p-8 rounded-[32px] bg-white/[0.02] border border-white/5 backdrop-blur-sm hover:border-emerald-500/20 transition-all group">
            <div class="flex flex-col md:flex-row gap-6">
              <div class="w-14 h-14 rounded-2xl bg-emerald-500/10 flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform">
                <Lock class="w-7 h-7 text-emerald-500" />
              </div>
              <div>
                <h2 class="text-2xl font-bold mb-4 text-white uppercase italic tracking-tight">
                  {{ t?.legal?.privacy?.section2?.title }}
                </h2>
                <p class="text-gray-400 leading-relaxed font-light text-lg">
                  {{ t?.legal?.privacy?.section2?.content }}
                </p>
              </div>
            </div>
          </div>

          <!-- Section 3 -->
          <div class="p-8 rounded-[32px] bg-white/[0.02] border border-white/5 backdrop-blur-sm hover:border-emerald-500/20 transition-all group">
            <div class="flex flex-col md:flex-row gap-6">
              <div class="w-14 h-14 rounded-2xl bg-emerald-500/10 flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform">
                <Eye class="w-7 h-7 text-emerald-500" />
              </div>
              <div>
                <h2 class="text-2xl font-bold mb-4 text-white uppercase italic tracking-tight">
                  {{ t?.legal?.privacy?.section3?.title }}
                </h2>
                <p class="text-gray-400 leading-relaxed font-light text-lg">
                  {{ t?.legal?.privacy?.section3?.content }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </Layout>
</template>

// examples/zenith-site/src/client/pages/Privacy.tsx
import { Head } from '@inertiajs/react'
import { motion } from 'framer-motion'
import { Shield, Lock, Eye } from 'lucide-react'
import React from 'react'
import { Footer } from '../components/Footer'
import { Navbar } from '../components/Navbar'
import { useTrans } from '../hooks/useTrans'

export default function Privacy() {
    const { trans } = useTrans()

    return (
        <div className="min-h-screen bg-zenith-void text-white selection:bg-zenith-accent selection:text-zenith-void overflow-x-hidden font-sans">
            <Head title={`${trans('privacy.title')} - Gravito Zenith`} />
            <Navbar />

            <section className="relative pt-32 pb-20 overflow-hidden">
                <div className="absolute inset-0 z-0">
                    <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[600px] bg-zenith-500/10 rounded-full blur-[120px] -translate-y-1/2" />
                    <div className="absolute inset-0 bg-grid-zenith opacity-10" />
                </div>

                <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.8 }}
                        className="text-center mb-16"
                    >
                        <h1 className="text-5xl lg:text-6xl font-bold tracking-tighter mb-4 text-glow">
                            {trans('privacy.title')}
                        </h1>
                        <p className="text-gray-500 font-mono text-xs uppercase tracking-widest">
                            {trans('privacy.lastUpdated')}
                        </p>
                    </motion.div>

                    <div className="space-y-12">
                        <LegalSection
                            icon={<Shield className="w-6 h-6 text-zenith-accent" />}
                            title={trans('privacy.section1.title')}
                            content={trans('privacy.section1.content')}
                        />
                        <LegalSection
                            icon={<Lock className="w-6 h-6 text-zenith-pulse" />}
                            title={trans('privacy.section2.title')}
                            content={trans('privacy.section2.content')}
                        />
                        <LegalSection
                            icon={<Eye className="w-6 h-6 text-zenith-stellar" />}
                            title={trans('privacy.section3.title')}
                            content={trans('privacy.section3.content')}
                        />
                    </div>
                </div>
            </section>

            <Footer />
        </div>
    )
}

function LegalSection({ icon, title, content }: { icon: React.ReactNode, title: string, content: string }) {
    return (
        <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="p-8 rounded-3xl zenith-glass border border-white/5 hover:border-white/10 transition-all"
        >
            <div className="flex items-start gap-6">
                <div className="w-12 h-12 rounded-xl bg-white/5 flex items-center justify-center flex-shrink-0">
                    {icon}
                </div>
                <div>
                    <h2 className="text-2xl font-bold mb-4 text-white/90">{title}</h2>
                    <p className="text-gray-400 leading-relaxed font-light">
                        {content}
                    </p>
                </div>
            </div>
        </motion.div>
    )
}
